language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN='99b8e533-ac5e-450a-af01-e16face1e215'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - andrey@laktyushin.com
    on_success: never # default: change
    on_failure: always # default: always