language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN='59314aa2-9bfc-46ac-b4d2-7137875cf64b'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - andrey@laktyushin.com
    on_success: never # default: change
    on_failure: always # default: always