language: java

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - openjdk17

sudo: false

notifications:
  email:
    recipients:
      - andrey@laktyushin.com
    on_success: never # default: change
    on_failure: always # default: always
